# Generated by Django 5.2 on 2025-04-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
