# Generated by Django 5.2 on 2025-05-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Api', '0002_authlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlog',
            name='event_type',
            field=models.CharField(choices=[('register', 'User Registration'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('logout', 'Logout')], max_length=50),
        ),
    ]
