# Generated by Django 5.2 on 2025-05-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Api', '0004_customuser_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uuid',
        ),
    ]
