# Generated by Django 5.2.3 on 2025-06-14 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Api', '0005_remove_customuser_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emainl_notifications', models.BooleanField(default=True)),
                ('autosave_enabled', models.BooleanField(default=True)),
                ('autosave_interval_minutes', models.PositiveIntegerField(default=5)),
                ('notify_on_delete', models.BooleanField(default=True)),
                ('notify_on_restore', models.BooleanField(default=True)),
                ('notify_on_autosave', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
