# Generated by Django 5.2.3 on 2025-06-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Api', '0006_usersettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='emainl_notifications',
            new_name='email_notifications',
        ),
    ]
