# Generated by Django 5.2 on 2025-05-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='uuid',
        ),
    ]
